---
# tasks file for openstack-securitygroup-grapher

# 1 - get instances information
# 2 - get security group and rules information

- name: verify needed variables
  assert:
    that: "{{ item }} is defined"
    msg: "{{ item }} need to be defined and must not be empty"
  with_items:
    - osggrapherCloudInfra

- name: verify if dot is installed
  shell: "dot -V"
  ignore_errors: true
  register: osggraphercmd_out

- name: alert if dot is not installed
  assert:
    that: osggraphercmd_out.rc == 0
    msg: "dot (from graphviz) has to be installed to use this role"

- name: Get instances information
  openstack.cloud.server_info:
    cloud: "{{ osggrapherCloudInfra }}"
  register: instances
  tags: instances
  when: osggrapherShowInstances

# - debug:
#     msg: "{{ item.name }}"
#   with_items: "{{ instances.openstack_servers }}"

- name: Get security groups and rules
  openstack.cloud.security_group_info:
    cloud: "{{ osggrapherCloudInfra }}"
  register: security_groups
  tags: security_groups

# - debug:
#     msg: "{{ item.name }}"
#   with_items: "{{ security_groups.security_groups }}"

- name: export sg graph
  template:
    src: fullsg-instances.dot.j2
    dest: "{{ osggrapherDotFileToRender }}"

- name: render graph
  shell: "dot -Tpng -o{{ osggrapherFileToRender}} {{ osggrapherDotFileToRender }}"
